version: "3.7"

services:
  app:
    build: .
    command: bash -c "make dev && node server.js"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # Modify these in your .env file
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./elm.json:/usr/src/app/elm.json
      - ./src:/usr/src/app/src
      - ./server.js:/usr/src/app/server.js
      - ./Makefile:/usr/src/app/Makefile

  watcher:
    build: .
    command: node watcher.js
    volumes:
      - ./elm.json:/usr/src/app/elm.json
      - ./Makefile:/usr/src/app/Makefile
      - ./watcher.js:/usr/src/app/watcher.js
      - ./src:/usr/src/app/src
